version: "3.9"

services:
  postgres:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_USER: hemanth
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres_database:
