"""status_maped

Revision ID: 3aa52d232510
Revises: f6233a20f691
Create Date: 2025-09-21 16:26:22.073461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa52d232510'
down_revision: Union[str, Sequence[str], None] = 'f6233a20f691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('workflows', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('nodes', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
