"""credentais_revamp

Revision ID: a18cf8e3cf58
Revises: af9578272974
Create Date: 2025-09-17 22:12:53.717217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a18cf8e3cf58'
down_revision: Union[str, Sequence[str], None] = 'af9578272974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('credentials', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('credentials', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('credentials_user_Id_fkey'), 'credentials', type_='foreignkey')
    op.create_foreign_key(None, 'credentials', 'users', ['user_id'], ['id'])
    op.drop_column('credentials', 'user_Id')
    op.drop_column('credentials', 'updated_At')
    op.drop_column('credentials', 'created_At')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('created_At', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('credentials', sa.Column('updated_At', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('credentials', sa.Column('user_Id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'credentials', type_='foreignkey')
    op.create_foreign_key(op.f('credentials_user_Id_fkey'), 'credentials', 'users', ['user_Id'], ['id'])
    op.drop_column('credentials', 'user_id')
    op.drop_column('credentials', 'updated_at')
    op.drop_column('credentials', 'created_at')
    # ### end Alembic commands ###
