"""status

Revision ID: f6233a20f691
Revises: a8380af06a54
Create Date: 2025-09-21 15:56:41.178038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6233a20f691'
down_revision: Union[str, Sequence[str], None] = 'a8380af06a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('status', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_workflow_executions_task_id'), table_name='workflow_executions')
    op.drop_column('workflow_executions', 'task_id')
    op.add_column('workflows', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'status')
    op.add_column('workflow_executions', sa.Column('task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_workflow_executions_task_id'), 'workflow_executions', ['task_id'], unique=True)
    op.drop_column('nodes', 'status')
    # ### end Alembic commands ###
