"""tool

Revision ID: d778aaad85fd
Revises: a1fd5c37f914
Create Date: 2025-09-23 13:48:16.075683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd778aaad85fd'
down_revision: Union[str, Sequence[str], None] = 'a1fd5c37f914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('workflows', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('nodes', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
