"""add waiting_node_id and execution_order

Revision ID: efad26900937
Revises: d778aaad85fd
Create Date: 2025-09-28 11:09:50.005641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efad26900937'
down_revision: Union[str, Sequence[str], None] = 'd778aaad85fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_executions', sa.Column('waiting_node_id', sa.UUID(), nullable=True))
    op.add_column('workflow_executions', sa.Column('execution_order', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_executions', 'execution_order')
    op.drop_column('workflow_executions', 'waiting_node_id')
    # ### end Alembic commands ###
